"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv


# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Clave secreta del proyecto (en produccion se carga desde variable de entorno).
# En desarrollo local se usa un valor por defecto. En produccion DEBE estar definida
# como variable de entorno para garantizar la seguridad del sistema.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure--j!z*bzy2vx@bc=nf-m8z5skrggpwb&i8+xk#r1u2)+)ute!fa'
)

# Modo depuracion (desactivado por defecto para seguridad en produccion).
# Activar solo en desarrollo local con la variable de entorno DEBUG=True.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.render.com', '.cgarcher.dev']

# Permitir hosts adicionales del servidor de despliegue (Render, Dokploy, etc.)
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_external_hostname:
    ALLOWED_HOSTS.append(render_external_hostname)

extra_hosts = os.environ.get('ALLOWED_HOSTS_EXTRA', '')
if extra_hosts:
    ALLOWED_HOSTS.extend(host.strip() for host in extra_hosts.split(',') if host.strip())


# Definicion de aplicaciones instaladas

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'voluntariado',
    # Permiso de seguridad que autoriza a React pedirle cosas a Django sin que el navegador lo bloquee
    'corsheaders',
    # Para instalar las herramientas de rest framework y poder mostrar y traducir los datos a json
    'rest_framework',
    'rest_framework.authtoken',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Base de datos local (SQLite en desarrollo, PostgreSQL en produccion)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'voluntariado_db',
    }
}

# Solo aplica la configuracion de DATABASE_URL si esta definida (produccion/Render).
# En desarrollo local se usa la base de datos SQLite configurada arriba.
if os.environ.get('DATABASE_URL'):
    db_from_env = dj_database_url.config(conn_max_age=500)
    DATABASES['default'].update(db_from_env)


# Validadores de contrasena

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internacionalizacion

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Archivos estaticos (CSS, JS, imagenes)

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Habilitar compresión de archivos estáticos en Whitenoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL del frontend (para enlaces en emails de bienvenida, reset de contrasena, etc.).
# En desarrollo apunta a localhost, en produccion se carga desde variable de entorno.
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Configuracion de CORS: solo los origenes autorizados pueden hacer peticiones.
# CORS_ALLOW_ALL_ORIGINS se desactiva por seguridad en produccion.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,https://voluntariado.cgarcher.dev'
    ).split(',')
    if origin.strip()
]

# En desarrollo local se puede activar CORS_ALLOW_ALL_ORIGINS=True desde el .env
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

# Origenes de confianza para solicitudes CSRF (necesario cuando frontend y backend
# estan en dominios diferentes o se usa HTTPS)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,https://voluntariado.cgarcher.dev'
    ).split(',')
    if origin.strip()
]

# Configuracion del backend de email.
# En desarrollo local usa la consola (imprime los emails en la terminal).
# En produccion se debe configurar un servidor SMTP real mediante variables de entorno.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@voluntariado.com')

# Configuracion SMTP para produccion (solo aplica si EMAIL_BACKEND es SMTP).
# Se cargan desde variables de entorno para no exponer credenciales.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'

# Configuracion DEFAULT_AUTO_FIELD para evitar warnings de Django
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'